export interface LexiconItem {
  term: string;
  meaning: string;
  tailwind: string;
  react: string;
  motion: string;
  notes?: string;
}

export const lexiconData: LexiconItem[] = [
  {
    term: '卡片',
    meaning: '獨立的內容區塊',
    tailwind: 'rounded-2xl border shadow-sm p-6',
    react: '<Card />',
    motion: '進場淡入 opacity/scale',
    notes: '通常包含標題、內容、操作按鈕',
  },
  {
    term: '陰影',
    meaning: '元素的立體層次',
    tailwind: 'shadow-sm/md/lg/xl/2xl',
    react: 'boxShadow style prop',
    motion: 'hover 時增加陰影',
    notes: '深色模式可用 ring 替代',
  },
  {
    term: '圓角',
    meaning: '元素邊角的弧度',
    tailwind: 'rounded-none/sm/md/lg/xl/2xl/full',
    react: 'borderRadius style',
    motion: '動態改變圓角',
    notes: '卡片通常用 rounded-xl 或 2xl',
  },
  {
    term: '間距',
    meaning: '元素之間的距離',
    tailwind: 'gap-* space-* p-* m-*',
    react: 'padding/margin props',
    motion: '動態調整間距',
    notes: '保持一致的間距系統',
  },
  {
    term: '按鈕',
    meaning: '可點擊的操作元素',
    tailwind: 'px-4 py-2 bg-* hover:* active:*',
    react: '<Button onClick />',
    motion: 'whileTap scale',
    notes: '最小 44x44px 觸控目標',
  },
  {
    term: '導航列',
    meaning: '網站主要導航',
    tailwind: 'flex justify-between sticky top-0',
    react: '<Navbar />',
    motion: '捲動時收合/展開',
    notes: '考慮行動版漢堡選單',
  },
  {
    term: '模態框',
    meaning: '覆蓋式對話框',
    tailwind: 'fixed inset-0 z-50',
    react: '<Modal isOpen />',
    motion: '淡入+縮放進場',
    notes: '需要背景遮罩和關閉按鈕',
  },
  {
    term: '表單',
    meaning: '資料輸入介面',
    tailwind: 'space-y-4 border rounded',
    react: '<Form onSubmit />',
    motion: '錯誤時震動',
    notes: '包含驗證和錯誤提示',
  },
  {
    term: '網格',
    meaning: '規律排列的布局',
    tailwind: 'grid grid-cols-* gap-*',
    react: 'CSS Grid or Flexbox',
    motion: 'stagger 子元素',
    notes: '響應式欄數變化',
  },
  {
    term: '標籤',
    meaning: '分類或狀態標記',
    tailwind: 'px-2 py-1 text-xs rounded-full',
    react: '<Badge />',
    motion: '出現時彈跳',
    notes: '使用語意顏色',
  },
  {
    term: '工具提示',
    meaning: '懸停顯示的說明',
    tailwind: 'absolute z-10 p-2 text-sm',
    react: '<Tooltip />',
    motion: 'fade + 位移',
    notes: '注意位置計算避免溢出',
  },
  {
    term: '進度條',
    meaning: '顯示完成百分比',
    tailwind: 'h-2 bg-gray-200 rounded-full',
    react: '<Progress value />',
    motion: '寬度動畫',
    notes: '可加入百分比文字',
  },
  {
    term: '骨架屏',
    meaning: '載入時的佔位元素',
    tailwind: 'animate-pulse bg-gray-200',
    react: '<Skeleton />',
    motion: '脈動動畫',
    notes: '保持與實際內容相似的結構',
  },
  {
    term: '麵包屑',
    meaning: '顯示當前位置路徑',
    tailwind: 'flex items-center space-x-2',
    react: '<Breadcrumb />',
    motion: '項目依序出現',
    notes: '使用 > 或 / 分隔',
  },
  {
    term: '分頁',
    meaning: '內容分頁導航',
    tailwind: 'flex gap-1',
    react: '<Pagination />',
    motion: '當前頁高亮動畫',
    notes: '顯示總頁數和當前頁',
  },
  {
    term: '下拉選單',
    meaning: '展開式選項列表',
    tailwind: 'absolute top-full mt-2',
    react: '<Dropdown />',
    motion: 'slide down + fade',
    notes: '點擊外部關閉',
  },
  {
    term: '切換開關',
    meaning: '二元狀態切換',
    tailwind: 'w-12 h-6 rounded-full',
    react: '<Switch checked />',
    motion: '滑動動畫',
    notes: '明確的開關狀態',
  },
  {
    term: '頭像',
    meaning: '使用者圖片',
    tailwind: 'w-10 h-10 rounded-full',
    react: '<Avatar src />',
    motion: '載入時淡入',
    notes: '提供預設圖片',
  },
  {
    term: '通知',
    meaning: '系統訊息提示',
    tailwind: 'fixed top-4 right-4',
    react: '<Toast />',
    motion: 'slide in + fade',
    notes: '自動消失計時',
  },
  {
    term: '側邊欄',
    meaning: '側邊導航區域',
    tailwind: 'w-64 h-full fixed/sticky',
    react: '<Sidebar />',
    motion: '滑入/滑出',
    notes: '行動版可收合',
  },
];